/*
 * Project: REPS – Renewable Energy Production System
 *
 * Course: Functional Programming
 *
 * Team Members:
 * Saikhansurtalt Sumiyabazar 002329527
 * Inthuja Inthumathan 002599632
 *
 * Description:
 * This file defines the console based presentation logic for the REPS system.
 * All output formatting and printing is isolated here to separate concerns
 * from core functional logic.
 */

package reps.view

import reps.model.*

/**
 * Responsible for displaying processed data to the console.
 *
 * This object performs side effects related to output only.
 * It does not modify data or contain any decision making logic.
 */
object ConsoleView:

  /**
   * Displays energy production records in a readable format.
   *
   * @param records
   *   A list of energy production records to display.
   */
  def showRecords(records: List[EnergyRecord]): Unit =
    if records.isEmpty then
      println("No energy records to display.")
    else
      records.foreach { r =>
        println(
          s"${r.timestamp} | ${r.source} | ${r.energyMWh} MWh"
        )
      }

  /**
   * Displays alert messages generated by the system.
   *
   * @param alerts
   *   A list of alerts to display.
   */
  def showAlerts(alerts: List[Alert]): Unit =
    if alerts.isEmpty then
      println("No alerts detected.")
    else
      alerts.foreach { alert =>
        println(s"ALERT: ${alert.message}")
      }