/*
 * Project: REPS – Renewable Energy Production System
 *
 * Course: Functional Programming
 *
 * Team Members:
 * Saikhansurtalt Sumiyabazar 002329527
 * Inthuja Inthumathan 002599632
 *
 * Description:
 * This file defines alert data types used to represent abnormal
 * or noteworthy conditions detected during energy data analysis.
 */

package reps.model

/**
 * Represents an alert generated by the REPS system.
 *
 * Alerts are modeled as immutable data values rather than
 * printed directly, allowing them to be processed, stored,
 * or displayed in a consistent way.
 */
sealed trait Alert:

  /** Human readable description of the alert. */
  def message: String


/**
 * Companion object for Alert types.
 *
 * Contains concrete alert implementations used by
 * the alert detection logic.
 */
object Alert:

  /**
   * Alert indicating that energy production has fallen
   * below a defined threshold for a specific energy source.
   *
   * @param source
   *   The energy source associated with the alert.
   * @param value
   *   The measured energy output in megawatt hours.
   */
  final case class LowOutput(
                              source: EnergySource,
                              value: Double
                            ) extends Alert:
    val message =
      s"Low energy output detected for $source: $value MWh"

  /**
   * Alert indicating that an expected energy source
   * is missing from the dataset.
   *
   * This may suggest a potential system malfunction
   * or data availability issue.
   *
   * @param source
   *   The missing energy source.
   */
  final case class Malfunction(
                                source: EnergySource
                              ) extends Alert:
    val message =
      s"Possible malfunction detected for $source"